henricm/ha-ferroamp

custom_components/ferroamp/config_flow.py, custom_components/ferroamp/const.py, custom_components/ferroamp/sensor.py, custom_components/ferroamp/strings.json, custom_components/ferroamp/translations/en.json, tests/test_config_flow.py, tests/test_sensor.py
It's now possible to set the precision for battery, current, energy, power, temperature and voltage in the option flow.
Closes #16
=> feat: change default precisions and make them configurable

custom_components/ferroamp/sensor.py, tests/test_sensor.py
Closes #26
@danielolsson100 I have removed the model from the name (this is then a breaking change for anyone with Gen2 SSO's since the entity id's will be different) and added it as model to the device instead.
=> feat: remove model-info from SSO-name

custom_components/ferroamp/const.py, custom_components/ferroamp/sensor.py, tests/test_sensor.py
@danielolsson100 Something like this? Would be nice to get the same for SSO from Ferroamp as well 😉
=> feat: add textual representation of ESO faultcodes as attributes

requirements.test.txt
We rely on the dependency from pytest-homeassistant-custom-component instead
=> chore: remove dependency on homeassistant

requirements.test.txt
We get this dependency from pytest-homeassistant-custom-component anyway
=> build: remove direct dependency on voluptous

custom_components/ferroamp/sensor.py, tests/test_sensor.py
The problem was that unit of measurement was set to empty string instead of None.
Started to introduce strict typing to allow it to be either a string or
None.
Closes #92
=> fix: make relay status history available

custom_components/ferroamp/sensor.py, tests/test_sensor.py
New sensor named "Available RMS current for load balancing"
Closes #95 
Supersedes #96 and #97
=> feat: add sensor for load balancing

custom_components/ferroamp/sensor.py
when battery level is below 10 today it selects mdi:battery-level-9 for example and this is not a valid icon so i have changed to utilize the built in icon helper for battery from home assistant.
=> fix: battery icon when below 10 percent is not valid

custom_components/ferroamp/sensor.py
Might fix #316. Could you try this change locally @mickecamino?
=> fix: don't store events if sensor is not present

custom_components/ferroamp/sensor.py, tests/test_sensor.py
Energy sensors seems to be 0 every now and then for some users.
This commit ignores such values before they reach the average
calculation.
This commit also moves the assignment of `SensorStateClass.TOTAL_INCREASING`
into energy sensor classes since they always are total increasing.
This way we can assume objects of this class are always total
increasing.
Refs #318
=> fix: ignore zero values for total-increasing energy sensors

custom_components/ferroamp/sensor.py, tests/test_sensor.py
Correct calculation of dc link voltage sensor state. Seems the values where reversed
fixes #364
=> fix: correct calculation dc link voltage sensor state

.devcontainer/devcontainer.json, .devcontainer/scripts/setup
avoids race condition on devcontainer creation by using postCreateCommand as these are run in parallel
=> chore: fix race condition in postCreateCommand

.devcontainer/config/configuration.yaml
set to True to allow breakpoints in async_setup or similar and debug the loading of the integration.
=> chore: add wait option to debug configuration

.vscode/launch.json
make remote debug configuration interactive for easier debugging of remote server
prompt for
=> chore(vscode): prompt for remote debug host

custom_components/ferroamp/sensor.py
If sensor data is missing in event, `EnergyFerroampSensor` will write a warning to log to on every update, even if `check_presence=True`
The reason for this behaviour is that being that the `check_presence` check is done in the base class.
The issue is fixed by adding an additional check in `EnergyFerroampSensor`.
This fix applies to all `EnergyFerroampSensor` with `check_presence=True`
- `Battery Energy Produced`
- `Battery Energy Consumed`
fixes #405
=> fix(sensor): do not log warning if sensor is not present

.pre-commit-config.yaml, custom_components/ferroamp/__init__.py, custom_components/ferroamp/const.py
Calling hass.config_entries.async_forward_entry_setup is deprecated and will be removed in Home Assistant 2025.6
Fixed issue with commitlint not working on node 23
=> chore: await hass.config_entries.async_forward_entry_setups

.github/conventional-changelog.js, .github/workflows/release.yaml
**Title:** ci: add conventional changelog configuration
**Description:**
This pull request introduces a custom configuration for the conventional changelog, enabling us to define specific types and their respective sections more effectively. Additionally, it updates the GitHub Actions workflow to utilize the newly specified configuration file path rather than the default preset, enhancing the changelog generation process. These changes aim to improve the clarity and organization of commit messages within the generated changelogs, ultimately leading to better project documentation and version history tracking. 
**Changes Included:**
- Custom configuration for the conventional changelog.
- Updated GitHub Actions workflow to reference the new configuration path.
By merging this PR, we can …
=> ci: add conventional changelog configuration 

CHANGELOG.md
Add detailed changelog entries for versions up to 1.14.2. 
Include bug fixes, features, and miscellaneous tasks to provide 
comprehensive release notes and improve documentation clarity. 
Update dependency versions for better performance and maintenance.
=> docs: add changelog for releases up to 1.14.2

tests/test_config_flow.py
Refactor the test for the options flow to use the updated import for 
the result type. This change enhances clarity by explicitly 
referencing `FlowResultType` and ensures compatibility with the 
latest structure of the Home Assistant testing framework.
=> feat(tests): update result type in config flow tests

.github/workflows/pythonpackage.yaml, README.md, hacs.json, requirements.dev.txt, requirements.test.txt
Updates Home Assistant to version 2024.12.0 in multiple files, ensuring 
compatibility with the latest features and fixes. Adjusts the Python version 
in CI configuration to 3.13 for improved performance. Updates the version 
of `pytest-homeassistant-custom-component` to 0.13.190 to leverage the 
latest testing enhancements. Modifies README to reflect the new 
Home Assistant version requirements.
=> chore(deps): update Home Assistant and related dependencies

pyproject.toml
Update the `asyncio_default_fixture_loop_scope` in the
`pyproject.toml` file to "function" to ensure that
fixtures using asyncio have the correct scope for testing.
This improves test reliability and isolates test cases
more effectively.
=> fix: set asyncio default fixture loop scope to function
