henricm/ha-ferroamp

custom_components/ferroamp/sensor.py, tests/test_sensor.py
Closes #19
Low hanging fruit 🍎
=> feat: add sensor for estimated grid frequency

README.md, info.md
=> fix: change link for Mosquitto bridge connections

custom_components/ferroamp/config_flow.py
@danielolsson100 Part 1 of split from #25
=> chore: fix typo

custom_components/ferroamp/sensor.py, tests/test_sensor.py
Closes #24
@danielolsson100 Part 3 of split of #25
=> feat: add ESM status sensor

custom_components/ferroamp/sensor.py, tests/test_sensor.py
@danielolsson100 Another missing sensor
=> feat: add missing ESM Rated Power sensor

custom_components/ferroamp/sensor.py
=> fix: register version-sensor earlier and actually write state to HA

custom_components/ferroamp/sensor.py, tests/test_sensor.py
=> fix: only migrate ESM entities that actually need migrating

README.md, custom_components/ferroamp/sensor.py, tests/test_sensor.py
=> feat: remove integration name from sensor names

custom_components/ferroamp/sensor.py, tests/test_sensor.py
=> fix: rename sensors for load balancing

README.md, info.md
Supersedes #65 
Supersedes #71
=> docs: how to setup the Energy Dashboard

custom_components/ferroamp/sensor.py, tests/test_sensor.py
@jonasbkarlsson Could this be a valid solution to the problem in #76 ? Would it introduce any strange side-effect? I don't see that the energy values ever should go backwards, right? @danielolsson100 Any thoughts?
=> Handle missing values

custom_components/ferroamp/sensor.py, tests/test_sensor.py
=> fix: handle unknown value for energy sensor

.github/commitlint.config.js, .github/workflows/commitlint.yaml
This should resolve the problem with dependabot updates failing the linter
=> ci: add config for commitlint

custom_components/ferroamp/sensor.py, tests/test_sensor.py
=> feat: make sure that 3-phase energy sensors are strictly increasing

custom_components/ferroamp/sensor.py, tests/test_sensor.py
=> fix: handle unknown value for percentage sensor

custom_components/ferroamp/sensor.py, tests/test_sensor.py
=> fix: make four more sensors total increasing

custom_components/ferroamp/sensor.py, hacs.json, requirements.test.txt, tests/test_sensor.py
A first stab at supporting the new entity naming style which will be available from next major release 2022.8.x. No merging until that is available at least I would say.
=> feat: migrate to new entity naming style

.github/workflows/hacs.yaml, README.md, custom_components/ferroamp/manifest.json
Added some requirements for being able to add this integration to hacs default.
=> feat: add this integration to hacs default

README.md
Before merging this i need some help from @argoyle:
1. Create a fork of https://github.com/hacs/default
2. Add "henricm/ha-ferroamp", to integration file.
3. Create a new PR to https://github.com/hacs/default with the content:
Topic: Adds new integration [henricm/ha-ferroamp]
Description:
Link to successful HACS action: https://github.com/henricm/ha-ferroamp/actions/runs/2816940946
Link to successful hassfest action (if integration): https://github.com/henricm/ha-ferroamp/actions/runs/2816940959
Then we should be good to go once that pr is merged :)
=> feat: updating readme.md

README.md
Something like this? @opsiorobinostlund @robinostlund @henricm
=> chore: add contribution info to readme

custom_components/ferroamp/sensor.py, tests/test_sensor.py
=> feat: only add sensors for loadbalancing if present in message

custom_components/ferroamp/sensor.py
Received events will now be logged on debug so enabling debug logging in HA for this integration will log all events received from EH.
Also log on info when we get zero-values to easier track if when this happens to users.
=> feat: added possibility to turn on debug logging of events

custom_components/ferroamp/sensor.py
=> fix: add control status sensor on init

README.md
=> docs: increasing scan interval for version scraper in README.md

custom_components/ferroamp/const.py, tests/test_sensor.py
=> Additional SSO Fault codes

custom_components/ferroamp/sensor.py, tests/test_sensor.py
=> feat: add separate entities per phase

.devcontainer/README.md, .devcontainer/config/configuration.yaml, .devcontainer/devcontainer.json, .devcontainer/requirements.txt, .devcontainer/scripts/develop, .devcontainer/scripts/setup, .vscode/launch.json, .vscode/settings.json, .vscode/tasks.json
Add vscode devcontainer configuration.
fixes #371
=> feat: vscode devcontainer configuration

custom_components/ferroamp/config_flow.py, custom_components/ferroamp/const.py, custom_components/ferroamp/sensor.py, custom_components/ferroamp/strings.json, custom_components/ferroamp/translations/en.json, tests/test_config_flow.py, tests/test_sensor.py
Closes #355 https://developers.home-assistant.io/blog/2023/02/08/sensor_presentation_rounding
=> feat: remove precision config since now builtin to HA

.github/workflows/pythonpackage.yaml, README.md, hacs.json, requirements.dev.txt, requirements.test.txt, tests/test_sensor.py
=> chore: update to 3.12 plus some fixes

release-please-config.json
Adds specific changelog sections to categorize commits by type. This
improves the clarity and organization of release notes for better
understanding of changes in each version. The new sections include
attributes for features, bug fixes, performance improvements,
documentation, styles, and more, ensuring a comprehensive overview
of updates.
=> feat(changelog): add custom sections for changelog types

.devcontainer/config/configuration.yaml, .devcontainer/devcontainer.json, .devcontainer/scripts/develop, .gitignore, .vscode/launch.json, .vscode/tasks.json, requirements.dev.txt
Use python 3.12, support debugging
=> chore: upgrade devcontainer to support 2024.6
